/* automatically generated by rust-bindgen 0.65.1 */

extern "C" {
    pub fn shmemcpy_api_init();
}
extern "C" {
    pub fn shmem_drain();
}
extern "C" {
    pub fn shmem_flush_cpu_cache(addr: *const ::std::os::raw::c_void, len: usize);
}
extern "C" {
    pub fn shmem_output_cpu_cache(addr: *const ::std::os::raw::c_void, len: usize);
}
extern "C" {
    pub fn shmem_memmove(
        shmemdest: *mut ::std::os::raw::c_void,
        src: *const ::std::os::raw::c_void,
        len: usize,
        flags: ::std::os::raw::c_uint,
    ) -> *mut ::std::os::raw::c_void;
}
extern "C" {
    pub fn shmem_memset(
        shmemdest: *mut ::std::os::raw::c_void,
        c: ::std::os::raw::c_int,
        len: usize,
        flags: ::std::os::raw::c_uint,
    ) -> *mut ::std::os::raw::c_void;
}
